### PR TITLE
Style the webpage and add display the image result in html after prediction

### PR DESCRIPTION
**Pull request by Alicia-Toom**

### CODE REVIEW

**Review by meDracula — CHANGES_REQUESTED** [review]
Enjoy the improved functionality on the post page.

However:
- Background image in GET page makes it hard to determine witch images is selected. It would be better with black background for both GET & POST. 
-  BUG of displaying images in GET where size of image is  "to large".

**Review by Antonsen2 — COMMENTED** [review]
Is there a reason to why save the image in a image_store and add a endpoint with image id?
It should work to only return the image sent in inside post function.

**Review by AndreasEliasson91 — COMMENTED** [review]
The design gets a bit messy when the uploaded image is displayed.
And how will this work with Markus object detection-functionality and design?

**Comment by meDracula** [comment]
Developer decision to separating previewing to big image size.

**Review by meDracula — APPROVED** [review]
LGTM

**Review by Antonsen2 — APPROVED** [review]

**Review by mattiasbarth — APPROVED** [review]

**Pull request merged**
